# Generated by Django 3.0.7 on 2025-11-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_household', '0002_householdtransactions_user_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdtransactions',
            name='user_household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_household_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
